
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 07 13:50:23 BRT 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIS = 3;
  public static final int PTVIRG = 2;
  public static final int error = 1;
  public static final int MENOS = 4;
  public static final int EOF = 0;
  public static final int INTEIRO = 5;
}

